sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install expect
  - npm install -g particle-cli

script:
  - echo "$(which particle)"
  - chmod +x travis-helper.sh
  - ./travis-helper.sh $email $pass
  - particle compile photon firmware/
