sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install expect
  - npm install -g particle-cli
  - export PARTICLE="$(which particle)"

script:
  - chmod +x travis-helper.sh
  - ./travis-helper.sh
