sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install expect figlet rubygems-integration
  - sudo gem install trollop ruby-paint
  - wget http://launchpadlibrarian.net/137808115/lolcat_42.0.99-1_all.deb
  - sudo dpkg --install lolcat_42.0.99-1_all.deb
  - npm install -g particle-cli

script:
  - ./particle-cli-login.sh $email $pass
  - particle compile photon firmware/
  
after_success:
  - curl -X POST -H "Content-Type: application/json" -d '{"value1":"was successful"}' "https://maker.ifttt.com/trigger/pushbullet/with/key/$ifttt"
  - figlet "It worked!" | lolcat
  
after_failure:
  - curl -X POST -H "Content-Type: application/json" -d '{"value1":"failed"}' "https://maker.ifttt.com/trigger/pushbullet/with/key/$ifttt"
  - figlet "Failed!" | lolcat
