sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install expect
  - npm install -g particle-cli

script:
  - ./particle-cli-login.sh $email $pass
  - particle compile photon firmware/

after_success:
  - curl -X POST https://maker.ifttt.com/trigger/pushbullet/with/key/$ifttt

after_failure:
  - curl -X POST https://maker.ifttt.com/trigger/pushbullet2/with/key/$ifttt
